# This is a basic workflow to help you get started with Actions

name: Package publication ğŸ“¦ 

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      SERVER_REPOSITORY: ${{ secrets.SERVER_REPOSITORY }}
      CLIENT_REPOSITORY: ${{ secrets.CLIENT_REPOSITORY }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_USER: ${{ github.actor }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        name: ğŸ—‚ Check out code
        
      - uses: actions/setup-java@v1
        name: â˜•ï¸ Set up JDK 15
        with:
          java-version: 15
        
      - name: ğŸ”“ Auth GithubPackages
        run: echo "$DOCKER_PASSWORD" | docker login docker.pkg.github.com -u $DOCKER_USER --password-stdin

      # Client package
      - name: ğŸ— Build the client Docker image
        run: docker build -t $CLIENT_REPOSITORY client

      - name: ğŸ· Tag the client Docker image
        run: |
          docker tag $CLIENT_REPOSITORY:latest $CLIENT_REPOSITORY:dev/beta

      - name: ğŸš€ Push client Docker image to Github package registry
        run: |
          docker push $CLIENT_REPOSITORY:dev/beta
          
      # Server package
      - name: ğŸ— Build the server Docker image
        run: |
          cd server && ./mvnw clean install
          docker build -t $SERVER_REPOSITORY .

      - name: ğŸ· Tag the server Docker image
        run: |
          docker tag $SERVER_REPOSITORY:latest $SERVER_REPOSITORY:dev/beta

      - name: ğŸš€ Push server Docker image to Github package registry
        run: |
          docker push $SERVER_REPOSITORY:dev/beta
